version: "3.6"

services:
  cms-springboot:
    image: "pilaniya1337/cms"
    ports:
      - "8082:8082"
    depends_on:
      - "cms-mysql"

  cms-mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cms_db
      - MYSQL_USER=cms_user
      - MYSQL_PASSWORD=cms_password
